languageCode = "en"
defaultContentLanguage = "en"
title = "GitHub Certified"
baseUrl = "https://ghcertified.com"

defaultContentLanguageInSubdir = false

theme = "hugo-theme-relearn"



[minify]
disableHTML = true
