[[shortcuts]]
name = "<i class='fab fa-github'></i> Repository"
identifier = "ds"
url = "https://github.com/FidelusAleksander/githubcertified"
weight = 10


[[shortcuts]]
name = "<i class='fas fa-fw fa-calendar'></i> Official Site"
identifier = "Certifications"
url = "https://resources.github.com/learn/certifications/"
weight = 20

[[shortcuts]]
name = "<i class='fas fa-hand-holding-heart'></i> Contribute"
identifier = "contribute"
url = "https://github.com/FidelusAleksander/githubcertified/contribute"
weight = 30


[[shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> GitHub Documentation"
identifier = "githubdoc"
url = "https://docs.github.com/en"
weight = 40
