[[shortcuts]]
name = "<i class='fab fa-github'></i> Repository"
identifier = "ds"
url = "https://github.com/FidelusAleksander/ghcertified"
weight = 10

[[shortcuts]]
name = "<i class='fas fa-hand-holding-heart'></i> Contribute"
identifier = "contribute"
url = "https://github.com/FidelusAleksander/ghcertified/contribute"
weight = 20

[[shortcuts]]
name = "<i class='fas fa-fw fa-calendar'></i> Official Site"
identifier = "Certifications"
url = "https://learn.github.com/certifications"
weight = 30

[[shortcuts]]
name = "<i class='fas fa-fw fa-comments'></i> Discussions"
identifier = "Discussions"
url = "https://github.com/FidelusAleksander/ghcertified/discussions"
weight = 40
