# Looks best on blue
# themeVariant = [ "auto", "blue", "relearn-bright", "relearn-light", "relearn-dark", "zen-light", "zen-dark", "neon", "learn", "green", "red" ]
# themeVariantAuto = [ "relearn-light", "relearn-dark" ]
themeVariant = "blue"

showVisitedLinks = false
disableBreadcrumb = false
disableNextPrev = false
disableSearch = false
disableHistory = true
disableLandingPageButton = true
disableSeoHiddenPages = false
hideAuthorDate = true


alwaysopen = false
editURL = "https://github.com/FidelusAleksander/ghcertified/edit/master/content/"
author.name = "Aleksander Fidelus"

# Disable the language switching button until the site is fully translated
disableLanguageSwitchingButton = false


# Images for OpenGraph
images = ["images/opengraph.png"]
