# Looks best on blue
# themeVariant = [ "auto", "blue", "relearn-bright", "relearn-light", "relearn-dark", "zen-light", "zen-dark", "neon", "learn", "green", "red" ]
# themeVariantAuto = [ "relearn-light", "relearn-dark" ]
themeVariant = "blue"

showVisitedLinks = false
disableBreadcrumb = false
disableNextPrev = false
disableSearch = false
disableHistory = true
disableLandingPageButton = true
disableSeoHiddenPages = false

alwaysopen = false
editURL = "https://github.com/FidelusAleksander/ghcertified/edit/master/content/"
author.name = "Aleksander Fidelus"


# Images for OpenGraph
images = ["images/opengraph.png"]

showLanguageSwitcher = true
additionalContentLanguage = ['en']

hideAuthorDate = true
